export const MOCK_TRADES = {
  'LIC-48291': {
    name: 'Jake Morrison',
    trade: 'Licensed Electrician',
    status: 'ACTIVE',
    licence: 'LIC-48291',
    expiry: '2026-11-30',
    issuer: 'NSW Fair Trading',
    since: '2015',
    insuranceValid: true,
    highRiskWork: true,
    asbestosCleared: true,
    rating: 4.8,
    reviews: 142,
    photo: 'JM',
    alerts: [],
    suburb: 'Surry Hills, NSW',
  },
  'PLB-77432': {
    name: 'Sandra Okafor',
    trade: 'Plumber & Drainer',
    status: 'ACTIVE',
    licence: 'PLB-77432',
    expiry: '2025-03-15',
    issuer: 'NSW Fair Trading',
    since: '2011',
    insuranceValid: true,
    highRiskWork: false,
    asbestosCleared: true,
    rating: 4.6,
    reviews: 87,
    photo: 'SO',
    alerts: ['⚠️ Licence expires soon — verify renewal'],
    suburb: 'Newtown, NSW',
  },
  'BLD-10293': {
    name: 'Tony Ferraro',
    trade: 'Builder — General',
    status: 'SUSPENDED',
    licence: 'BLD-10293',
    expiry: '2024-08-01',
    issuer: 'VIC Building Authority',
    since: '2009',
    insuranceValid: false,
    highRiskWork: false,
    asbestosCleared: false,
    rating: 2.9,
    reviews: 33,
    photo: 'TF',
    alerts: ['🚨 Licence suspended', '🚨 Insurance not verified', '🚨 Asbestos cert missing'],
    suburb: 'Fitzroy, VIC',
  },
}
