export const MOCK_TRADES = {
  'LIC-48291': {
    name: 'Jake Morrison',
    trade: 'Licensed Electrician',
    status: 'ACTIVE',
    licence: 'LIC-48291',
    expiry: '2026-11-30',
    issuer: 'NSW Fair Trading',
    since: '2015',
    insuranceValid: true,
    highRiskWork: true,
    asbestosCleared: true,
    rating: 4.8,
    reviews: 142,
    photo: 'JM',
    alerts: [],
    suburb: 'Surry Hills, NSW',
  },
  'PLB-77432': {
    name: 'Sandra Okafor',
    trade: 'Plumber & Drainer',
    status: 'ACTIVE',
    licence: 'PLB-77432',
    expiry: '2025-03-15',
    issuer: 'NSW Fair Trading',
    since: '2011',
    insuranceValid: true,
    highRiskWork: false,
    asbestosCleared: true,
    rating: 4.6,
    reviews: 87,
    photo: 'SO',
    alerts: ['⚠️ Licence expires soon — verify renewal'],
    suburb: 'Newtown, NSW',
  },
  'BLD-10293': {
    name: 'Tony Ferraro',
    trade: 'Builder — General',
    status: 'SUSPENDED',
    licence: 'BLD-10293',
    expiry: '2024-08-01',
    issuer: 'VIC Building Authority',
    since: '2009',
    insuranceValid: false,
    highRiskWork: false,
    asbestosCleared: false,
    rating: 2.9,
    reviews: 33,
    photo: 'TF',
    alerts: ['🚨 Licence suspended', '🚨 Insurance not verified', '🚨 Asbestos cert missing'],
    suburb: 'Fitzroy, VIC',
  },
  'QLD-55221': {
    name: 'Emma Walters',
    trade: 'Carpentry & Joinery',
    status: 'ACTIVE',
    licence: 'QLD-55221',
    expiry: '2027-05-20',
    issuer: 'QBCC Queensland',
    since: '2018',
    insuranceValid: true,
    highRiskWork: false,
    asbestosCleared: false,
    rating: 4.9,
    reviews: 56,
    photo: 'EW',
    alerts: [],
    suburb: 'South Brisbane, QLD',
  },
  'WA-88331': {
    name: 'Mark Henderson',
    trade: 'Gas Fitter',
    status: 'ACTIVE',
    licence: 'WA-88331',
    expiry: '2025-12-10',
    issuer: 'Building Services WA',
    since: '2012',
    insuranceValid: true,
    highRiskWork: true,
    asbestosCleared: false,
    rating: 4.7,
    reviews: 92,
    photo: 'MH',
    alerts: [],
    suburb: 'Perth, WA',
  },
  'SA-11223': {
    name: 'Lisa Chen',
    trade: 'Refrigeration & AC',
    status: 'ACTIVE',
    licence: 'SA-11223',
    expiry: '2026-09-15',
    issuer: 'CBS South Australia',
    since: '2020',
    insuranceValid: true,
    highRiskWork: false,
    asbestosCleared: false,
    rating: 4.5,
    reviews: 21,
    photo: 'LC',
    alerts: [],
    suburb: 'Adelaide, SA',
  },
  'ACT-99001': {
    name: 'David Miller',
    trade: 'Bricklayer',
    status: 'ACTIVE',
    licence: 'ACT-99001',
    expiry: '2024-11-01',
    issuer: 'Access Canberra',
    since: '2005',
    insuranceValid: true,
    highRiskWork: false,
    asbestosCleared: false,
    rating: 4.8,
    reviews: 110,
    photo: 'DM',
    alerts: ['⚠️ Licence expiring soon'],
    suburb: 'Canberra, ACT',
  },
  'TAS-44556': {
    name: 'Sarah Boyle',
    trade: 'Painter & Decorator',
    status: 'ACTIVE',
    licence: 'TAS-44556',
    expiry: '2028-01-30',
    issuer: 'CBOS Tasmania',
    since: '2022',
    insuranceValid: true,
    highRiskWork: false,
    asbestosCleared: false,
    rating: 4.9,
    reviews: 15,
    photo: 'SB',
    alerts: [],
    suburb: 'Hobart, TAS',
  },
}
